### PR TITLE
36 develop permutations to work on edfacts files

### PR DESCRIPTION
**Pull request by VT-AOE-DMAD-Drew-Bennett**
Class Initialization:

Updated version where class defines organization_columns as a combination of parent_organization and child_organization.

Method: cross_suppression:

Implements a cross-suppression algorithm to redact sensitive data in the log dataframe.
Handles specific cases where either parent or child organization data is missing, renaming the redaction columns and merging this data back into the log dataframe.

### CODE REVIEW

**Comment by amstutzg1** [comment]
@VT-AOE-DMAD-Drew-Bennett is there anywhere in the code where we automatically suppress 0's and/or should we be suppressing 0's automatically?

**Comment by amstutzg1** [comment]
> > @VT-AOE-DMAD-Drew-Bennett is there anywhere in the code where we automatically suppress 0's and/or should we be suppressing 0's automatically?
> 
> In one redact zero method zero is redacted. @amstutzg1

Looking at the output of df_apply_anonymization in the apply_anonymization notebook, I am seeing rows 25 and 27 both not being redacted but counts of 0. It looks like the one_redact_zero function does not explicitly look for 0's in the dataset and redact them; it appears to be doing it based on some grouping.

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
> > > @VT-AOE-DMAD-Drew-Bennett is there anywhere in the code where we automatically suppress 0's and/or should we be suppressing 0's automatically?
> > 
> > 
> > In one redact zero method zero is redacted. @amstutzg1
> 
> Looking at the output of df_apply_anonymization in the apply_anonymization notebook, I am seeing rows 25 and 27 both not being redacted but counts of 0. It looks like the one_redact_zero function does not explicitly look for 0's in the dataset and redact them; it appears to be doing it based on some grouping.

I am not completely following. Do you want to meet tomorrow and review? I am free all day tomorrow.

**Comment by amstutzg1** [comment]
@VT-AOE-DMAD-Drew-Bennett I took a look at the issue we talked about earlier where 0's were not being suppressed when they should have. I made a couple changes to the one_redact_zero function that I _think_ have fixed the issue without reintroducing any new issues. Going to commit them now.

**Comment by aemnathanclinton** [comment]
This PR is getting pretty big.  I'm going to push this through and we can create new tickets and feature branches to resolve any unfinished work or defects.

**Review by aemnathanclinton — APPROVED** [review]

**Pull request merged**
